using System;
using System.Reflection;
using System.Threading.Tasks;

namespace CrawlerApp
{
    static class Program
    {
        public static async Task Main(string[] args)
        {
            var versionString = Assembly.GetEntryAssembly()?
                                       .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?
                                       .InformationalVersion
                                       .ToString();

            Console.WriteLine($"botsay: v{versionString}");
            ShowBot("Welcome!");

            if (args.Length < 4)
            {
                Console.WriteLine("-------------");
                Console.WriteLine("\nUsage:");
                Console.WriteLine("botsay : No arguments enough !!");
            }
            else
            {
                Console.WriteLine("-------------");
                Console.WriteLine("botsay : Running....!\n");
                await new Crawler(args).Execute();
            }
        }

        static void ShowBot(string message)
        {
            string bot = $"\n        {message}";
            bot += @"
    __________________
                      \
                       \
                          ....
                          ....'
                           ....
                        ..........
                    .............'..'..
                 ................'..'.....
               .......'..........'..'..'....
              ........'..........'..'..'.....
             .'....'..'..........'..'.......'.
             .'..................'...   ......
             .  ......'.........         .....
             .    _            __        ......
            ..    #            ##        ......
           ....       .                 .......
           ......  .......          ............
            ................  ......................
            ........................'................
           ......................'..'......    .......
        .........................'..'.....       .......
     ........    ..'.............'..'....      ..........
   ..'..'...      ...............'.......      ..........
  ...'......     ...... ..........  ......         .......
 ...........   .......              ........        ......
.......        '...'.'.              '.'.'.'         ....
.......       .....'..               ..'.....
   ..       ..........               ..'........
          ............               ..............
         .............               '..............
        ...........'..              .'.'............
       ...............              .'.'.............
      .............'..               ..'..'...........
      ...............                 .'..............
       .........                        ..............
        .....
";
            Console.WriteLine(bot);
        }
    }
}
